// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pack
IntegerVector pack(IntegerVector starts, IntegerVector ends, bool use_dp);
RcppExport SEXP _segmentpacker_pack(SEXP startsSEXP, SEXP endsSEXP, SEXP use_dpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_dp(use_dpSEXP);
    rcpp_result_gen = Rcpp::wrap(pack(starts, ends, use_dp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_segmentpacker_pack", (DL_FUNC) &_segmentpacker_pack, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_segmentpacker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
